### ISSUE TITLE
MalformedURLException running badgeup init

### ISSUE THREAD

**Issue by Mohron** [BadgeUp/sponge-client#10]
I am getting the following error after following the documentation:

```[02:28:14] [Server thread/INFO] [nucleus/]: Server ran the command: /badgeup init
[02:28:14] [pool-2-thread-2892/ERROR] [Sponge/luckperms]: The Scheduler tried to run the task badgeup-sponge-client-A-4397 owned by Plugin{id=badgeup-sponge-client, name=BadgeUp Sponge Client, version=1.0.5, description=Easily add Achievements and Awards to your Sponge server, url=https://www.badgeup.io/, authors=[Robert Herhold], source=/home/minecraft/multicraft/servers/sf3/./plugins/badgeup-sponge-client-v1.0.5.jar}, but an error occured.
java.lang.RuntimeException: java.net.MalformedURLException: no protocol: 3m2eoddy1d/criteria
	at com.mashape.unirest.http.HttpClientHelper.prepareRequest(HttpClientHelper.java:183) ~[HttpClientHelper.class:?]
	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:131) ~[HttpClientHelper.class:?]
	at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68) ~[BaseRequest.class:?]
	at io.badgeup.sponge.command.executor.BadgeUpInitCommandExecutor$BadgeUpInitRunnable.meatLoverAchievement(BadgeUpInitCommandExecutor.java:142) ~[BadgeUpInitCommandExecutor$BadgeUpInitRunnable.class:?]
	at io.badgeup.sponge.command.executor.BadgeUpInitCommandExecutor$BadgeUpInitRunnable.run(BadgeUpInitCommandExecutor.java:68) ~[BadgeUpInitCommandExecutor$BadgeUpInitRunnable.class:?]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:138) ~[Task$Builder.class:1.10.2-2221-5.1.0-BETA-2135]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:183) ~[SchedulerBase.class:1.10.2-2221-5.1.0-BETA-2135]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.net.MalformedURLException: no protocol: 3m2eoddy1d/criteria
	at java.net.URL.<init>(URL.java:593) ~[?:1.8.0_101]
	at java.net.URL.<init>(URL.java:490) ~[?:1.8.0_101]
	at java.net.URL.<init>(URL.java:439) ~[?:1.8.0_101]
	at com.mashape.unirest.http.HttpClientHelper.prepareRequest(HttpClientHelper.java:171) ~[HttpClientHelper.class:?]
	... 11 more
```
[BadgeUp Log](https://hastebin.com/acupixenun.rb)

**Comment by MarkHerhold** [comment]
@Mohron Thank you for reporting this issue! We'll take a look to see what went wrong.

**Comment by RobertHerhold** [comment]
See [v1.1.0](https://github.com/BadgeUp/sponge-client/releases/tag/v1.1.0) for the release fixing this
