### ISSUE TITLE
AbstractMethodError on Forge server load

### ISSUE THREAD

**Issue by Mohron** [BadgeUp/sponge-client#12]
Build from 32b727cb28da68e310e0e559f1f7e74122b0247a
SF: spongeforge-1.10.2-2221-5.1.0-BETA-2136

```java
10.02 17:12:54 [Server] Server thread/ERROR [Sponge]: Could not pass FMLServerStartingEvent to Plugin{id=badgeup-sponge-client, name=BadgeUp Sponge Client, version=1.0.5, description=Easily add Achievements and Awards to your Sponge server, url=https://www.badgeup.io/, authors=[Robert Herhold], source=/./plugins/BadgeUp-1.0.5-all.jar}
10.02 17:12:54 [Server] INFO java.lang.AbstractMethodError
10.02 17:12:54 [Server] INFO at org.spongepowered.common.event.filters.EventFilter_BadgeUpSpongeEventListener_event46.filter(Unknown Source) ~[?:?]
10.02 17:12:54 [Server] INFO at org.spongepowered.common.event.listener.EventListener_BadgeUpSpongeEventListener_event46.handle(Unknown Source) ~[?:?]
10.02 17:12:54 [Server] INFO at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2221-5.1.0-BETA-2136]
10.02 17:12:54 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:301) [SpongeModEventManager.class:1.10.2-2221-5.1.0-BETA-2136]
10.02 17:12:54 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:330) [SpongeModEventManager.class:1.10.2-2221-5.1.0-BETA-2136]
10.02 17:12:54 [Server] INFO at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:234) [SpongeMod.class:1.10.2-2221-5.1.0-BETA-2136]
10.02 17:12:54 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
10.02 17:12:54 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
10.02 17:12:54 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
10.02 17:12:54 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
10.02 17:12:54 [Server] INFO at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.10.2.jar:?]
10.02 17:12:54 [Server] INFO at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.10.2.jar:?]
10.02 17:12:54 [Server] INFO at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.10.2.jar:?]
10.02 17:12:54 [Server] INFO at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.10.2.jar:?]
10.02 17:12:54 [Server] INFO at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.10.2.jar:?]
10.02 17:12:54 [Server] INFO at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) [LoadController.class:?]
10.02 17:12:54 [Server] INFO at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) [LoadController.class:?]
10.02 17:12:54 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
10.02 17:12:54 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
10.02 17:12:54 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
10.02 17:12:54 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
10.02 17:12:54 [Server] INFO at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.10.2.jar:?]
10.02 17:12:54 [Server] INFO at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.10.2.jar:?]
10.02 17:12:54 [Server] INFO at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.10.2.jar:?]
10.02 17:12:54 [Server] INFO at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.10.2.jar:?]
10.02 17:12:54 [Server] INFO at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.10.2.jar:?]
10.02 17:12:54 [Server] INFO at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzb000(LoadController.java:552) [LoadController.class:?]
10.02 17:12:54 [Server] INFO at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) [LoadController.class:?]
10.02 17:12:54 [Server] INFO at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:855) [Loader.class:?]
10.02 17:12:54 [Server] INFO at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:292) [FMLCommonHandler.class:?]
10.02 17:12:54 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:293) [ld.class:?]
10.02 17:12:54 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
10.02 17:12:54 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

**Comment by RobertHerhold** [comment]
@Mohron I've already [reported this issue](https://github.com/SpongePowered/SpongeForge/issues/1154) on the SpongeForge repo. There's nothing that I can do about it, but I'll keep this issue open until it is resolved.

**Comment by RobertHerhold** [comment]
@Mohron I should note though that this shouldn't impact the normal function of the plugin - it's just an error on startup
