### ISSUE TITLE
IndexOutOfBounds

### ISSUE THREAD

**Issue by MarkHerhold** [BadgeUp/sponge-client#27]
This impossible error popped up in a user's logs.
```
[10:25:24] [Server thread/ERROR] [Sponge]: Could not pass SpawnEntityEvent$Custom$Impl to Plugin{id=badgeup, name=BadgeUp Sponge Client, version=2.1.4, description=Easily add Achievements and Awards to your Sponge server, url=https://www.badgeup.io/, authors=[Robert Herhold], source=/foo/plugins/badgeup-sponge-client-v2.1.4.jar}
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_131]
    at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_131]
    at io.badgeup.sponge.eventlistener.BadgeUpEventListener$7.provide(BadgeUpEventListener.java:136) ~[BadgeUpEventListener$7.class:?]
    at io.badgeup.sponge.eventlistener.BadgeUpEventListener$7.provide(BadgeUpEventListener.java:132) ~[BadgeUpEventListener$7.class:?]
    at io.badgeup.sponge.eventlistener.BadgeUpEventListener.processEvent(BadgeUpEventListener.java:143) ~[BadgeUpEventListener.class:?]
    at io.badgeup.sponge.eventlistener.GeneralEventListener.spawnEntity(GeneralEventListener.java:116) ~[GeneralEventListener.class:?]
```

**Comment by RobertHerhold** [comment]
Resolved by #28
